### PR TITLE
[#25] Add Sidebar component

### LINKED ISSUE #25: #25 Sidebar component
- Uses Button, Icon Button, WeatherIcon, Weather Title, Current Place, Temperature components
- Add background image

### PR DESCRIPTION
**Pull request by inovux**
closes #25 

I finished the sidebar and came up with the following layout:

Screen Shot 2020-11-25 at 9 27 19 AM

Let me know what you guys think, and want to change anything :)

### CODE REVIEW

**Review by hananina — APPROVED** [review]
it fits the browser height, looks good to me🙌

**Comment by hananina** [comment]
just noticed that the mobile version of this sidebar seems have not implemented yet🤔? スクリーンショット 2020-11-27 10 34 48

**Comment by inovux** [comment]
@hananina Your right! let me take a look at that!

**Comment by inovux** [comment]
@mrpeterhanley and @hananina Please check if you have time :)

**Review by mrpeterhanley — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
