### PR TITLE
36 add search sidebar component

### PR DESCRIPTION
**Pull request by mrpeterhanley**
Component is used like this: `<SearchSidebar />`

search-sidebar

### CODE REVIEW

**Comment by mrpeterhanley** [comment]
@inovux Sorry I had created this new branch from your Sidebar component. But it seemed your Sidebar component was quite far behind the current Develop branch. That's why all the previous commits is from when I rebased this component from the current Develop branch

**Comment by inovux** [comment]
@mrpeterhanley how come there are so many file changes for this PR :O? Kinda lost to see what you actually worked on xD

**Comment by mrpeterhanley** [comment]
@inovux The last 3 commits are what I actually worked on

**Comment by inovux** [comment]
> @inovux The last 3 commits are what I actually worked on

@mrpeterhanley Alright, maybe we can see what goes wrong if you show me how your merge the branches together. If you have some time let me know then we can walk through it together real quick.

**Comment by mrpeterhanley** [comment]
@inovux So should I merge the branches together?

**Review by inovux — APPROVED** [review]

**Pull request merged**
